matrix:
  include:
    - language: node_js
      go:
        - 1.12.x
      node_js:
        - "10"
      dist: bionic
      install:
        - ./install.sh
        - cd common/nodejs; npm install ; cd -
        - sudo apt-get install -y softhsm2
      script:
        - ./docker.sh
        - node cc/golang/diagnose/test/
        - node test
        - ./test/hsm.sh

