language: node_js
node_js:
  - "8"
dist: bionic
install:
  - ./install.sh
deploy:
  - provider: script
    script: echo no deployment plan; exit 1
    on:
      branch: release-1.4
  - provider: script
    script: echo no deployment plan; exit 1
    on:
      branch: master

