# TODO
version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    network_mode: delphiNetwork
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - $HOME/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/astri.org/tlsca/tlsca.astri.org-cert.pem:/etc/prometheus/tlsca.astri.org-cert.pem
      - $HOME/Documents/delphi-fabric/config/ca-crypto-config/ordererOrganizations/delphi/tlsca/tlsca.delphi-cert.pem:/etc/prometheus/tlsca.delphi-cert.pem
