version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run:
          command: git branch --set-upstream-to=origin/release-1.4 release-1.4
      - run:
          command: ./install.sh

      - run:
          command: ./docker.sh
