version: 1
jobs:
  build:
    docker:
      - image: node:8

    steps:
      - checkout

      - run:
          name: install
          command: ./install.sh

      - run:
          name: fabricNetwork
          command: ./docker.sh
