version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.10

    steps:
      - checkout
      - run:
          command: apt update;
      - run:
          command: apt -qq install -y git
      - run:
          command: git checkout -b release-1.4; git branch --set-upstream-to=origin/release-1.4 release-1.4;
      - run:
          command: ssh -o StrictHostKeyChecking=no git@github.com; git remote set-url origin https://github.com/davidkhala/delphi-fabric.git
      - run:
          command: ./install.sh

      - run:
          command: ./docker.sh
