Profiles:
  delphiGenesis:
    Capabilities:
      V1_4_3: true
    Policies: &ref_1
      Readers:
        Type: ImplicitMeta
        Rule: ANY Readers
      Writers:
        Type: ImplicitMeta
        Rule: ANY Writers
      Admins:
        Type: ImplicitMeta
        Rule: MAJORITY Admins
    Orderer:
      BatchTimeout: 1s
      Addresses: {}
      BatchSize:
        MaxMessageCount: 1
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
      Capabilities:
        V1_4_2: true
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: ANY Readers
        Writers:
          Type: ImplicitMeta
          Rule: ANY Writers
        Admins:
          Type: ImplicitMeta
          Rule: MAJORITY Admins
        BlockValidation:
          Type: ImplicitMeta
          Rule: ANY Writers
      OrdererType: kafka
      Kafka:
        Brokers:
          - 'kafka0:9092'
          - 'kafka1:9092'
          - 'kafka2:9092'
          - 'kafka3:9092'
      Organizations:
        - Name: icdd.astri.org
          ID: ICDDMSP
          MSPDir: /home/davidliu/Documents/delphi-fabric/config/ca-crypto-config/ordererOrganizations/icdd.astri.org/msp
          Policies:
            Readers:
              Type: Signature
              Rule: OR('ICDDMSP.member')
            Writers:
              Type: Signature
              Rule: OR('ICDDMSP.member')
            Admins:
              Type: Signature
              Rule: OR('ICDDMSP.admin')
          OrdererEndpoints:
            - 'orderer0.icdd.astri.org:7050'
            - 'orderer1.icdd.astri.org:7050'
            - 'orderer2.icdd.astri.org:7050'
    Consortiums:
      SampleConsortium:
        Organizations:
          - Name: astri.org
            ID: ASTRIMSP
            MSPDir: /home/davidliu/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/astri.org/msp
            Policies:
              Readers:
                Type: Signature
                Rule: OR('ASTRIMSP.member')
              Writers:
                Type: Signature
                Rule: OR('ASTRIMSP.member')
              Admins:
                Type: Signature
                Rule: OR('ASTRIMSP.admin')
            OrdererEndpoints: &ref_0
              - 'orderer0.icdd.astri.org:7050'
              - 'orderer1.icdd.astri.org:7050'
              - 'orderer2.icdd.astri.org:7050'
          - Name: icdd
            ID: icddMSP
            MSPDir: /home/davidliu/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/icdd/msp
            Policies:
              Readers:
                Type: Signature
                Rule: OR('icddMSP.member')
              Writers:
                Type: Signature
                Rule: OR('icddMSP.member')
              Admins:
                Type: Signature
                Rule: OR('icddMSP.admin')
            OrdererEndpoints: *ref_0
  allchannel:
    Policies: *ref_1
    Capabilities:
      V1_4_3: true
    Consortium: SampleConsortium
    Application:
      Policies: *ref_1
      Organizations:
        - Name: astri.org
          ID: ASTRIMSP
          MSPDir: /home/davidliu/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/astri.org/msp
          Policies:
            Readers:
              Type: Signature
              Rule: OR('ASTRIMSP.member')
            Writers:
              Type: Signature
              Rule: OR('ASTRIMSP.member')
            Admins:
              Type: Signature
              Rule: OR('ASTRIMSP.admin')
          AnchorPeers:
            - {}
        - Name: icdd
          ID: icddMSP
          MSPDir: /home/davidliu/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/icdd/msp
          Policies:
            Readers:
              Type: Signature
              Rule: OR('icddMSP.member')
            Writers:
              Type: Signature
              Rule: OR('icddMSP.member')
            Admins:
              Type: Signature
              Rule: OR('icddMSP.admin')
          AnchorPeers:
            - {}
      Capabilities:
        V1_4_2: true
  extrachannel:
    Policies: *ref_1
    Capabilities:
      V1_4_3: true
    Consortium: SampleConsortium
    Application:
      Policies: *ref_1
      Organizations:
        - Name: astri.org
          ID: ASTRIMSP
          MSPDir: /home/davidliu/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/astri.org/msp
          Policies:
            Readers:
              Type: Signature
              Rule: OR('ASTRIMSP.member')
            Writers:
              Type: Signature
              Rule: OR('ASTRIMSP.member')
            Admins:
              Type: Signature
              Rule: OR('ASTRIMSP.admin')
          AnchorPeers:
            - {}
        - Name: icdd
          ID: icddMSP
          MSPDir: /home/davidliu/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/icdd/msp
          Policies:
            Readers:
              Type: Signature
              Rule: OR('icddMSP.member')
            Writers:
              Type: Signature
              Rule: OR('icddMSP.member')
            Admins:
              Type: Signature
              Rule: OR('icddMSP.admin')
          AnchorPeers:
            - {}
      Capabilities:
        V1_4_2: true
  anchorPeers:
    Application:
      Organizations:
        - Name: astri.org
          AnchorPeers:
            - Host: peer0.astri.org
              Port: 7051
            - Host: peer1.astri.org
              Port: 7051
        - Name: icdd
          AnchorPeers:
            - Host: peer0.icdd
              Port: 7051
            - Host: peer1.icdd
              Port: 7051
