Profiles:
  delphiGenesis:
    Capabilities:
      V1_3: true
    Orderer:
      BatchTimeout: 1s
      BatchSize:
        MaxMessageCount: 1
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
      Capabilities:
        V1_1: true
      OrdererType: kafka
      Addresses:
        - 'orderer0.ICDD.ASTRI.org:7050'
        - 'orderer1.ICDD.ASTRI.org:7050'
        - 'orderer2.ICDD.ASTRI.org:7050'
      Kafka:
        Brokers:
          - 'kafka0:9092'
          - 'kafka1:9092'
          - 'kafka2:9092'
          - 'kafka3:9092'
      Organizations:
        - Name: ICDD.ASTRI.org
          ID: ICDDMSP
          MSPDir: /home/mediconcen/Documents/delphi-fabric/config/ca-crypto-config/ordererOrganizations/ICDD.ASTRI.org/msp
    Consortiums:
      SampleConsortium:
        Organizations:
          - Name: ASTRI.org
            ID: ASTRIMSP
            MSPDir: /home/mediconcen/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/ASTRI.org/msp
          - Name: icdd
            ID: icdd
            MSPDir: /home/mediconcen/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/icdd/msp
  allchannel:
    Capabilities:
      V1_3: true
    Consortium: SampleConsortium
    Application:
      Organizations:
        - Name: ASTRI.org
          ID: ASTRIMSP
          MSPDir: /home/mediconcen/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/ASTRI.org/msp
          AnchorPeers:
            - {}
        - Name: icdd
          ID: icdd
          MSPDir: /home/mediconcen/Documents/delphi-fabric/config/ca-crypto-config/peerOrganizations/icdd/msp
          AnchorPeers:
            - {}
      Capabilities:
        V1_3: true
  anchorPeers:
    Application:
      Organizations:
        - Name: ASTRI.org
          AnchorPeers:
            - Host: peer0.ASTRI.org
              Port: 7051
        - Name: icdd
          AnchorPeers:
            - Host: peer0.icdd
              Port: 7051
